apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-edit
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-edit
subjects:
  - kind: ServiceAccount
    name: jenkins-edit
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
