apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-token
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-token
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: edit
  name: kube-system
